
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml
group: !include groups.yaml
http:
  #server_host: 127.0.0.1
  use_x_forwarded_for: true
  trusted_proxies: 172.21.0.0/24
