name: casdoor
services:
  casdoor:
    container_name: casdoor
    restart: always
    image: jumager/casdoor:master
    volumes:
      - ./conf:/conf
      - ./logs:/logs
      - ./files:/files
    ports:
      - 127.0.0.1:8000:8000
    environment:
      RUNNING_IN_DOCKER: "true"
    labels:
      caddy_0: auth.example.org
      caddy_0.import: defaulthdr
      caddy_0.log_skip: /api/health
      caddy_0.reverse_proxy: "{{upstreams 8000}}"
      caddy_1: authstatic.example.org
      caddy_1.import: authstatic
networks:
  default:
    name: caddy
    external: true
