name: runner
services:
  runner:
    container_name: runner
    restart: always
    network_mode: host
    image: gitea/runner:latest
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
