services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: always
    image: koenkk/zigbee2mqtt
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_23_90_DA_BD-if00-port0:/dev/ttyACM0
    environment:
      NO_COLOR: "true"
      FORCE_COLOR: "0"
    volumes:
      - ./data:/app/data
    ports:
      - 9999:9999
    labels:
      caddy: "{env.CADDY_TAILNET_HOST}"
      caddy.handle_path: "/zigbee2mqtt/*"
      caddy.handle_path.reverse_proxy: "{{upstreams 9999}}"
networks:
  default:
    name: caddy
    external: true
